-- LAB | SQL Joins

USE sakila;

-- 1. List the number of films per category.

SELECT 
	c.name AS category_name,
	COUNT(fc.film_id) AS number_of_films
FROM 
	film_category AS fc
INNER JOIN
	category AS c ON fc.category_id = c.category_id
GROUP BY
	c.name
ORDER BY
	number_of_films DESC;
    
-- 2. Retrieve the store ID, city, and country for each store.

SELECT
	s.store_id,
    ci.city,
    co.country
FROM 
	store AS s
INNER JOIN 
	address AS a ON s.address_id = a.address_id
INNER JOIN 
	city AS ci ON a.city_id = ci.city_id
INNER JOIN 
	country AS co ON ci.country_id = co.country_id;
    
-- 3. Calculate the total revenue generated by each store in dollars.

SELECT
	i.store_id,
	SUM(p.amount) AS total_revenue
FROM
	payment AS p
INNER JOIN
	rental AS r ON p.rental_id = r.rental_id
INNER JOIN
	inventory AS i ON r.inventory_id = i.inventory_id
GROUP BY
	i.store_id
ORDER BY
	total_revenue DESC;
    
-- 4. Determine the average running time of films for each category.

SELECT
    c.name AS category_name,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM
    film_category AS fc
INNER JOIN
    category AS c ON fc.category_id = c.category_id
INNER JOIN
    film AS f ON fc.film_id = f.film_id
GROUP BY
    c.name
ORDER BY
    average_running_time DESC;
    
    



    



